/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  basic_orderquantity: () => import("@/views/basic/orderQuantity/index.vue"),
  basic_productprice: () => import("@/views/basic/productPrice/index.vue"),
  "bill_bill-calculation-config": () => import("@/views/bill/bill-calculation-config/index.vue"),
  "bill_bill-item-config": () => import("@/views/bill/bill-item-config/index.vue"),
  "bill_bill-month-record": () => import("@/views/bill/bill-month-record/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "inventory_ics-inventory": () => import("@/views/inventory/ics-inventory/index.vue"),
  "inventory_inventory-details": () => import("@/views/inventory/inventory-details/index.vue"),
  "inventory_return-supplier": () => import("@/views/inventory/return-supplier/index.vue"),
  "inventory_transfer-orders": () => import("@/views/inventory/transfer-orders/index.vue"),
  purchase_inorders: () => import("@/views/purchase/inOrders/index.vue"),
  purchase_suggestion: () => import("@/views/purchase/suggestion/index.vue"),
};
