/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  basic_address: () => import("@/views/basic/address/index.vue"),
  basic_carrier: () => import("@/views/basic/carrier/index.vue"),
  basic_client: () => import("@/views/basic/client/index.vue"),
  basic_dictionary: () => import("@/views/basic/dictionary/index.vue"),
  "basic_operation-relation": () => import("@/views/basic/operation-relation/index.vue"),
  "basic_product-audits": () => import("@/views/basic/product-audits/index.vue"),
  basic_product: () => import("@/views/basic/product/index.vue"),
  "basic_product_modules_add-or-update": () => import("@/views/basic/product/modules/add-or-update/index.vue"),
  basic_project: () => import("@/views/basic/project/index.vue"),
  basic_supplier: () => import("@/views/basic/supplier/index.vue"),
  basic_warehouse: () => import("@/views/basic/warehouse/index.vue"),
  "config_product-audit-config": () => import("@/views/config/product-audit-config/index.vue"),
  "edi_mdm-synch-task": () => import("@/views/edi/mdm-synch-task/index.vue"),
  home: () => import("@/views/home/index.vue"),
};
