/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'basic',
    path: '/basic',
    component: 'layout.base',
    meta: {
      title: 'basic',
      i18nKey: 'route.basic'
    },
    children: [
      {
        name: 'basic_orderquantity',
        path: '/basic/orderquantity',
        component: 'view.basic_orderquantity',
        meta: {
          title: 'basic_orderquantity',
          i18nKey: 'route.basic_orderquantity'
        }
      },
      {
        name: 'basic_productprice',
        path: '/basic/productprice',
        component: 'view.basic_productprice',
        meta: {
          title: 'basic_productprice',
          i18nKey: 'route.basic_productprice'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      constant: true,
      icon: 'ic:round-home'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'purchase',
    path: '/purchase',
    component: 'layout.base',
    meta: {
      title: 'purchase',
      i18nKey: 'route.purchase'
    },
    children: [
      {
        name: 'purchase_inorders',
        path: '/purchase/inorders',
        component: 'view.purchase_inorders',
        meta: {
          title: 'purchase_inorders',
          i18nKey: 'route.purchase_inorders'
        }
      }
    ]
  }
];
