/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'basic',
    path: '/basic',
    component: 'layout.base',
    meta: {
      title: 'basic',
      i18nKey: 'route.basic'
    },
    children: [
      {
        name: 'basic_orderquantity',
        path: '/basic/orderquantity',
        component: 'view.basic_orderquantity',
        meta: {
          title: 'basic_orderquantity',
          i18nKey: 'route.basic_orderquantity'
        }
      },
      {
        name: 'basic_productprice',
        path: '/basic/productprice',
        component: 'view.basic_productprice',
        meta: {
          title: 'basic_productprice',
          i18nKey: 'route.basic_productprice'
        }
      }
    ]
  },
  {
    name: 'bill',
    path: '/bill',
    component: 'layout.base',
    meta: {
      title: 'bill',
      i18nKey: 'route.bill'
    },
    children: [
      {
        name: 'bill_bill-calculation-config',
        path: '/bill/bill-calculation-config',
        component: 'view.bill_bill-calculation-config',
        meta: {
          title: 'bill_bill-calculation-config',
          i18nKey: 'route.bill_bill-calculation-config'
        }
      },
      {
        name: 'bill_bill-item-config',
        path: '/bill/bill-item-config',
        component: 'view.bill_bill-item-config',
        meta: {
          title: 'bill_bill-item-config',
          i18nKey: 'route.bill_bill-item-config'
        }
      },
      {
        name: 'bill_bill-month-record',
        path: '/bill/bill-month-record',
        component: 'view.bill_bill-month-record',
        meta: {
          title: 'bill_bill-month-record',
          i18nKey: 'route.bill_bill-month-record'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      constant: true,
      icon: 'ic:round-home'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'inventory',
    path: '/inventory',
    component: 'layout.base',
    meta: {
      title: 'inventory',
      i18nKey: 'route.inventory'
    },
    children: [
      {
        name: 'inventory_ics-inventory',
        path: '/inventory/ics-inventory',
        component: 'view.inventory_ics-inventory',
        meta: {
          title: 'inventory_ics-inventory',
          i18nKey: 'route.inventory_ics-inventory'
        }
      },
      {
        name: 'inventory_inventory-details',
        path: '/inventory/inventory-details',
        component: 'view.inventory_inventory-details',
        meta: {
          title: 'inventory_inventory-details',
          i18nKey: 'route.inventory_inventory-details'
        }
      },
      {
        name: 'inventory_return-supplier',
        path: '/inventory/return-supplier',
        component: 'view.inventory_return-supplier',
        meta: {
          title: 'inventory_return-supplier',
          i18nKey: 'route.inventory_return-supplier'
        }
      },
      {
        name: 'inventory_transfer-orders',
        path: '/inventory/transfer-orders',
        component: 'view.inventory_transfer-orders',
        meta: {
          title: 'inventory_transfer-orders',
          i18nKey: 'route.inventory_transfer-orders'
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'purchase',
    path: '/purchase',
    component: 'layout.base',
    meta: {
      title: 'purchase',
      i18nKey: 'route.purchase'
    },
    children: [
      {
        name: 'purchase_inorders',
        path: '/purchase/inorders',
        component: 'view.purchase_inorders',
        meta: {
          title: 'purchase_inorders',
          i18nKey: 'route.purchase_inorders'
        }
      },
      {
        name: 'purchase_suggestion',
        path: '/purchase/suggestion',
        component: 'view.purchase_suggestion',
        meta: {
          title: 'purchase_suggestion',
          i18nKey: 'route.purchase_suggestion'
        }
      }
    ]
  }
];
